services:
  forum-frontend:
    image: blackfox89/myrepository:forum-frontend
    build:
      context: .
      dockerfile: Dockerfile_development
    container_name: forum-frontend
    ports:
      - 8082:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
